apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: promhttp
  namespace: istio-system
spec:
  actions:
    - handler: handler.prometheus
      instances:
        - requestcount.metric
        - requestduration.metric
        - requestsize.metric
        - responsesize.metric
        - requesttotalsize.metric
  match: context.protocol == "http" || context.protocol == "grpc"
