apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: fluentd
spec:
  actions:
  - handler: handler.fluentd
    instances:
    - sleep-log.logentry
  match: context.protocol == "http" && source.labels["app"] == "sleep"